#!/usr/bin/env node

var Program = require('commander');
var fs = require('fs');
var NodeGit = require('nodegit');
var Repository = NodeGit.Repository;
var clone = NodeGit.Clone.clone;
var rimraf = require('rimraf');
var Promise = require('bluebird').Promise;
var replace = require('replace');

Program
  .parse(process.argv);

var name = Program.args;

if (!name.length) {
  console.error('must give a name after "new" (ex: reapp new myname)');
  process.exit(1);
}

if (name.length > 1)
  console.error('sorry, we don\'t support multiple names');

var name = name[0];

console.log();
console.log('creating new reapp folder for: %s...', name);

var url = 'git://github.com/reapp/reapp-starter.git';
var dest = process.cwd() + '/' + name;
var opts = {
  bare: true
};

if (fs.existsSync(dest))
  console.log('error! location already exists');
else
  start();

function start() {
  cloneRepo()
    .then(deleteGitFolder)
    .then(initGit)
    .then(replaceGivenNameInApp)
    .then(npmInstall)
    .then(finish);
}

function cloneRepo() {
  return clone(url, dest, opts);
}

function deleteGitFolder() {
  return new Promise(function(resolve, reject) {
    rimraf(dest + '/.git', function(err, data) {
      if (err) return reject(err);
      resolve(data);
    })
  });
}

function initGit() {
  return Repository.init(dest + '/.git', 0);
}

function replaceGivenNameInApp() {
  return new Promise(function(resolve, reject) {
    replace({
      regex: '{{reappName}}',
      replacement: name,
      paths: [dest],
      recursive: true,
      silent: true
    });

    resolve();
  });
}

function npmInstall() {
  return new Promise(function(resolve, reject) {
    process.chdir(dest);

    var exec = require('child_process').exec, child;
    child = exec('npm install', function(error, stdout, stderr) {
      if (error) reject(error);
      console.log(stdout);
      console.log(stderr);
    });
  });
}

function finish() {
  console.log('ok');
  console.log();
}