#!/usr/bin/env node

if (process.argv.length === 2) {
  process.argv.push('--help');
}

var Program = require('commander');

Program
  .version(require('./package.json').version)
  .command('new [name]', 'creates a directory with a new reapp base installed')
  .command('run', 'runs a reapp application');

Program.parse(process.argv);