#!/usr/bin/env node

var Program = require('commander');

Program
  .version(require('./package.json').version)
  .command('new [name]', 'creates a directory with a new reapp base installed')
  .command('run', 'runs a reapp application')
  .parse(process.argv);

// defaults to run
if (!Program.args.length) {
  var exec = require('child_process').spawn;
  var child = exec('./reapp-run');

  child.stdout.on('data', function(data) {
      console.log('stdout: ' + data);
  });
  child.stderr.on('data', function(data) {
      console.log('stdout: ' + data);
  });
  child.on('close', function(code) {
      console.log('closing code: ' + code);
  });
}