#!/usr/bin/env node

var Program = require('commander');
var Pack = require('reapp-pack');
var buildConfig = require('reapp-pack/config/webpack.build.js');
var makeBuildDir = require('./lib/makeBuildDir');

Program
  .option('-d, --debug', 'output extra information for debugging')
  .option('-c, --config <path>', 'provide a config [path] for webpack')
  .option('--nolink', 'dont link webpack modules to ./server_modules')
  .parse(process.argv);

var opts = {
  dir: process.cwd(),
  debug: !!Program.debug,
  linkModules: !Program.nolink
};

makeBuildDir(opts.dir, run);

// relative path for config
if (Program.config && Program.config.indexOf('./') === 0)
  Program.config = opts.dir + Program.config.slice(1);

if (!Program.config)
  Program.config = Pack.makeConfig(buildConfig, opts);

if (opts.debug) {
  console.log('CLI received opts:');
  console.dir(opts);
  console.log();
}

function run() {
  Pack.webpack(Program.config, opts);
}