#!/usr/bin/env node

var Program = require('commander');
var colors = require('colors');
var fs = require('fs');
var rimraf = require('rimraf');
var replace = require('replace');
var Promise = require('bluebird').Promise;
var mkdirp = require('mkdirp');

Program
  .option('-d, --debug', 'output extra information for debugging')
  .parse(process.argv);

var name = Program.args;

if (!name.length) {
  console.log('must give a name after "new" (ex: reapp new myname)'.red);
  process.exit(1);
}

if (name.length > 1) {
  console.log('sorry, we don\'t support multiple names'.red);
  process.exit(1);
}

var name = name[0];

console.log();
console.log('Creating new reapp folder for: %s...'.green, name);

var dest = process.cwd() + '/' + name;

if (fs.existsSync(dest))
  console.log('Error! This directory already exists'.red);
else
  start();

function start() {
  makeFolder()
    .then(cloneRepo)
    .then(deleteGitFolder)
    .then(initGit)
    .then(replaceGivenNameInApp)
    .then(npmInstall)
    // .then(npmDedupe)
    .then(finish)
    .catch(function(err) {
      console.log("\n", 'Error'.bold.red);
      console.log(err);
    });
}

function makeFolder() {
  return new Promise(function(resolve, reject) {
    mkdirp(dest, function(err) {
      if (err)
        reject(err);
      else
        resolve();
    });
  });
}

function cloneRepo() {
  return promiseProcess('git clone --depth=1 git@github.com:reapp/reapp-starter.git ' + dest);
}

function deleteGitFolder() {
  return new Promise(function(resolve, reject) {
    rimraf(dest + '/.git', function(err, data) {
      if (err) return reject(err);
      resolve(data);
    })
  });
}

function initGit() {
  return promiseProcess('git init');
}

function replaceGivenNameInApp() {
  return new Promise(function(resolve, reject) {
    console.log('Inserting your name...'.green);
    replace({
      regex: '{{reappName}}',
      replacement: name,
      paths: [dest],
      recursive: true,
      silent: true
    });

    resolve();
  });
}

function npmInstall() {
  return promiseProcess('npm install');
}

function npmDedupe() {
  return promiseProcess('npm dedupe react');
}

function promiseProcess(cmd) {
  return new Promise(function(resolve, reject) {
    console.log('Running '+cmd+'...'.green);
    process.chdir(dest);

    var exec = require('child_process').exec, child;
    child = exec(cmd, handleChildProcess.bind(this, resolve, reject));
  });
}

function handleChildProcess(resolve, reject, error, stdout, stderr) {
  if (error)
    return reject(error);

  if (Program.debug)
    console.log(stderr);

  resolve();
}

function finish() {
  console.log('Done!'.green.bold);
  console.log();
}